[package]
name = "liquid-staking"
version = "0.0.0"
authors = [ "Sorin Petreasca <sorin.petreasca@multiversx.com>",]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.itertools]
version = "0.10.1"
default-features = false

[dependencies.elrond-wasm]
version = "0.38.0"

[dev-dependencies.elrond-wasm-debug]
version = "0.38.0"

[dependencies.elrond-wasm-modules]
version = "0.38.0"

[dependencies.delegation-mock]
path = "../delegation-mock"