[package]
name = "liquid-staking-abi"

version = "0.0.0"
authors = [ "Sorin Petreasca <sorin.petreasca@multiversx.com>",]
edition = "2021"
publish = false

[dependencies.liquid-staking]
path = ".."

[dependencies.elrond-wasm]
version = "0.38.0"

[dependencies.elrond-wasm-debug]
version = "0.38.0"

